export const labels = {
  brand: "VehicleTracker",
  common: {
    apply: "Apply",
    cancel: "Reset",
    close: "Close",
    delete: "Delete",
    edit: "Edit",
    loading: "Loading...",
    new: "New",
    next: "Next",
    noResults: "No records found.",
    previous: "Previous",
    save: "Save",
    view: "View",
    create: "Create",
    preview: "Preview",
    upload: "Upload",
    export: "Export",
    reset: "Reset",
  },
  navigation: {
    search: "Search Vehicles",
    management: "Vehicle Management",
    upload: "Vehicle Upload",
    users: "User Management",
    profile: "Profile",
    logout: "Logout",
  },
  vehicle: {
    title: "Vehicle Management",
    searchTitle: "Search Vehicles",
    createTitle: "Create Vehicle",
    editTitle: "Edit Vehicle",
    filters: "Vehicle Filters",
    baseModelName: "Base Model Name",
    variantName: "Variant Name",
    variants: "Variants",
    addVariant: "Add Variant",
    save: "Save Vehicle",
    details: "Vehicle Details",
    noVariants: "No variants available.",
    loadingVariants: "Loading variants...",
  },
  user: {
    title: "User Management",
    username: "Username",
    email: "Email",
    password: "Password",
    role: "Role",
    access: "Application Access",
    status: "Account Status",
    grant: "Grant Access",
    revoke: "Revoke Access",
    create: "Create User",
    initialPassword: "Initial password defaults to the configured value.",
  },
  auth: {
    signIn: "Sign In",
    register: "Register",
    currentPassword: "Current Password",
    newPassword: "New Password",
    confirmPassword: "Confirm Password",
    forgotPassword: "Forgot Password",
    resetPassword: "Reset Password",
    otpCode: "Verification Code",
    registerHeader: "Create account",
    registrationPending: "Registration complete. An administrator must grant application access before you can sign in.",
  },
} as const;

export const identifierLabels = {
  rlf_id: "RLF ID",
  rm_id: "RM ID",
  ip_id: "IP ID",
  rm_rlf_band: "RM/RLF Band",
  ip_band: "IP Band",
  evap_id: "EVAP ID",
  pr_id: "PR ID",
  df_id: "DF ID",
  ob_id: "OB ID",
  er_id: "ER ID",
  pems_id: "PEMS ID",
} as const;
